# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'esatraj.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ESATrajWindow(object):
    def setupUi(self, ESATrajWindow):
        ESATrajWindow.setObjectName("ESATrajWindow")
        ESATrajWindow.resize(1190, 859)
        self.centralwidget = QtWidgets.QWidget(ESATrajWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ComPortSelect = QtWidgets.QComboBox(self.centralwidget)
        self.ComPortSelect.setGeometry(QtCore.QRect(50, 100, 111, 22))
        self.ComPortSelect.setObjectName("ComPortSelect")
        self.LabelComMac = QtWidgets.QLabel(self.centralwidget)
        self.LabelComMac.setGeometry(QtCore.QRect(50, 80, 61, 16))
        self.LabelComMac.setObjectName("LabelComMac")
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectButton.setGeometry(QtCore.QRect(50, 160, 111, 23))
        self.ConnectButton.setObjectName("ConnectButton")
        self.StartPlotButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartPlotButton.setGeometry(QtCore.QRect(30, 760, 111, 23))
        self.StartPlotButton.setObjectName("StartPlotButton")
        self.ClearPlotButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClearPlotButton.setGeometry(QtCore.QRect(30, 800, 111, 23))
        self.ClearPlotButton.setObjectName("ClearPlotButton")
        self.ComStatusDisplay = QtWidgets.QLabel(self.centralwidget)
        self.ComStatusDisplay.setGeometry(QtCore.QRect(40, 200, 111, 16))
        self.ComStatusDisplay.setObjectName("ComStatusDisplay")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 230, 111, 16))
        self.label_5.setObjectName("label_5")
        self.DataCountDisplay = QtWidgets.QLineEdit(self.centralwidget)
        self.DataCountDisplay.setEnabled(True)
        self.DataCountDisplay.setGeometry(QtCore.QRect(40, 250, 111, 20))
        self.DataCountDisplay.setReadOnly(False)
        self.DataCountDisplay.setObjectName("DataCountDisplay")
        self.EnableLog = QtWidgets.QCheckBox(self.centralwidget)
        self.EnableLog.setGeometry(QtCore.QRect(50, 130, 121, 16))
        self.EnableLog.setObjectName("EnableLog")
        self.StartCSVButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartCSVButton.setGeometry(QtCore.QRect(40, 310, 111, 23))
        self.StartCSVButton.setObjectName("StartCSVButton")
        self.PlotPlaneSelect = QtWidgets.QComboBox(self.centralwidget)
        self.PlotPlaneSelect.setGeometry(QtCore.QRect(40, 480, 111, 22))
        self.PlotPlaneSelect.setObjectName("PlotPlaneSelect")
        self.PlotPlaneSelect.addItem("")
        self.PlotPlaneSelect.addItem("")
        self.PlotPlaneSelect.addItem("")
        self.PlotPlaneSelect.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 460, 101, 16))
        self.label_4.setObjectName("label_4")
        self.Enable_ConnectByCOM = QtWidgets.QRadioButton(self.centralwidget)
        self.Enable_ConnectByCOM.setGeometry(QtCore.QRect(50, 20, 83, 16))
        self.Enable_ConnectByCOM.setChecked(True)
        self.Enable_ConnectByCOM.setObjectName("Enable_ConnectByCOM")
        self.buttonGroup = QtWidgets.QButtonGroup(ESATrajWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Enable_ConnectByCOM)
        self.Enable_ConnectByMAC = QtWidgets.QRadioButton(self.centralwidget)
        self.Enable_ConnectByMAC.setGeometry(QtCore.QRect(50, 50, 83, 16))
        self.Enable_ConnectByMAC.setObjectName("Enable_ConnectByMAC")
        self.buttonGroup.addButton(self.Enable_ConnectByMAC)
        self.InputMacAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.InputMacAddress.setGeometry(QtCore.QRect(50, 100, 113, 20))
        self.InputMacAddress.setObjectName("InputMacAddress")
        self.LoadCSVButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadCSVButton.setGeometry(QtCore.QRect(40, 350, 111, 23))
        self.LoadCSVButton.setObjectName("LoadCSVButton")
        self.Enable_YUp = QtWidgets.QRadioButton(self.centralwidget)
        self.Enable_YUp.setGeometry(QtCore.QRect(50, 400, 87, 16))
        self.Enable_YUp.setObjectName("Enable_YUp")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(ESATrajWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.Enable_YUp)
        self.Enable_ZUp = QtWidgets.QRadioButton(self.centralwidget)
        self.Enable_ZUp.setGeometry(QtCore.QRect(50, 430, 87, 16))
        self.Enable_ZUp.setChecked(True)
        self.Enable_ZUp.setObjectName("Enable_ZUp")
        self.buttonGroup_2.addButton(self.Enable_ZUp)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 530, 61, 16))
        self.label.setObjectName("label")
        self.PlotPosition = QtWidgets.QLabel(self.centralwidget)
        self.PlotPosition.setGeometry(QtCore.QRect(200, 10, 941, 741))
        self.PlotPosition.setText("")
        self.PlotPosition.setObjectName("PlotPosition")
        self.PlotNavPosition = QtWidgets.QLabel(self.centralwidget)
        self.PlotNavPosition.setGeometry(QtCore.QRect(200, 780, 951, 41))
        self.PlotNavPosition.setText("")
        self.PlotNavPosition.setObjectName("PlotNavPosition")
        self.PlotRangeFrom = QtWidgets.QSlider(self.centralwidget)
        self.PlotRangeFrom.setGeometry(QtCore.QRect(50, 550, 111, 22))
        self.PlotRangeFrom.setSingleStep(10)
        self.PlotRangeFrom.setOrientation(QtCore.Qt.Horizontal)
        self.PlotRangeFrom.setObjectName("PlotRangeFrom")
        self.PlotRangeTo = QtWidgets.QSlider(self.centralwidget)
        self.PlotRangeTo.setGeometry(QtCore.QRect(50, 580, 111, 22))
        self.PlotRangeTo.setSingleStep(10)
        self.PlotRangeTo.setProperty("value", 99)
        self.PlotRangeTo.setOrientation(QtCore.Qt.Horizontal)
        self.PlotRangeTo.setObjectName("PlotRangeTo")
        self.PlotRangeFromInput = QtWidgets.QLineEdit(self.centralwidget)
        self.PlotRangeFromInput.setGeometry(QtCore.QRect(10, 550, 31, 20))
        self.PlotRangeFromInput.setObjectName("PlotRangeFromInput")
        self.PlotRangeToInput = QtWidgets.QLineEdit(self.centralwidget)
        self.PlotRangeToInput.setGeometry(QtCore.QRect(10, 580, 31, 20))
        self.PlotRangeToInput.setObjectName("PlotRangeToInput")
        self.AnimationSpeed = QtWidgets.QSlider(self.centralwidget)
        self.AnimationSpeed.setGeometry(QtCore.QRect(50, 660, 111, 22))
        self.AnimationSpeed.setMinimum(1)
        self.AnimationSpeed.setMaximum(1000)
        self.AnimationSpeed.setSingleStep(10)
        self.AnimationSpeed.setProperty("value", 10)
        self.AnimationSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.AnimationSpeed.setObjectName("AnimationSpeed")
        self.AnimationSpeedInput = QtWidgets.QLineEdit(self.centralwidget)
        self.AnimationSpeedInput.setGeometry(QtCore.QRect(10, 660, 31, 20))
        self.AnimationSpeedInput.setObjectName("AnimationSpeedInput")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 640, 91, 16))
        self.label_2.setObjectName("label_2")
        self.PlayAnimationButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlayAnimationButton.setGeometry(QtCore.QRect(30, 700, 111, 23))
        self.PlayAnimationButton.setObjectName("PlayAnimationButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 750, 118, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 620, 118, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(30, 520, 118, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(40, 390, 118, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(40, 290, 118, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        ESATrajWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ESATrajWindow)
        self.statusbar.setObjectName("statusbar")
        ESATrajWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ESATrajWindow)
        QtCore.QMetaObject.connectSlotsByName(ESATrajWindow)

    def retranslateUi(self, ESATrajWindow):
        _translate = QtCore.QCoreApplication.translate
        ESATrajWindow.setWindowTitle(_translate("ESATrajWindow", "ESATraj Plotter"))
        self.LabelComMac.setText(_translate("ESATrajWindow", "COM Port"))
        self.ConnectButton.setText(_translate("ESATrajWindow", "Connect"))
        self.StartPlotButton.setText(_translate("ESATrajWindow", "Start Plot"))
        self.ClearPlotButton.setText(_translate("ESATrajWindow", "Clear Plot"))
        self.ComStatusDisplay.setText(_translate("ESATrajWindow", "Disconnected"))
        self.label_5.setText(_translate("ESATrajWindow", "Data Received "))
        self.DataCountDisplay.setText(_translate("ESATrajWindow", "0"))
        self.EnableLog.setText(_translate("ESATrajWindow", "Terminal Log"))
        self.StartCSVButton.setText(_translate("ESATrajWindow", "Save CSV"))
        self.PlotPlaneSelect.setItemText(0, _translate("ESATrajWindow", " - "))
        self.PlotPlaneSelect.setItemText(1, _translate("ESATrajWindow", "XY"))
        self.PlotPlaneSelect.setItemText(2, _translate("ESATrajWindow", "XZ"))
        self.PlotPlaneSelect.setItemText(3, _translate("ESATrajWindow", "YZ"))
        self.label_4.setText(_translate("ESATrajWindow", "2D Plane View"))
        self.Enable_ConnectByCOM.setText(_translate("ESATrajWindow", "By COM"))
        self.Enable_ConnectByMAC.setText(_translate("ESATrajWindow", "By MAC"))
        self.LoadCSVButton.setText(_translate("ESATrajWindow", "Load CSV"))
        self.Enable_YUp.setText(_translate("ESATrajWindow", "Y Up"))
        self.Enable_ZUp.setText(_translate("ESATrajWindow", "Z Up"))
        self.label.setText(_translate("ESATrajWindow", "Plot Range"))
        self.PlotRangeFromInput.setText(_translate("ESATrajWindow", "0"))
        self.PlotRangeToInput.setText(_translate("ESATrajWindow", "99"))
        self.AnimationSpeedInput.setText(_translate("ESATrajWindow", "10"))
        self.label_2.setText(_translate("ESATrajWindow", "Animation Speed"))
        self.PlayAnimationButton.setText(_translate("ESATrajWindow", "Play Animation"))

